blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView, CreateBlogList, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list',BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>',BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('createblogs/', CreateBlogList, name='createblogs'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls', namespace='Catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    body = models.TextField(verbose_name='Содержимое')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    preview = models.ImageField(upload_to='blog/photo', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )
    views_count = models.IntegerField(default=0, verbose_name="Просмотры")
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано'
    )


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'is_published', 'preview')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'is_published', 'preview')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


def CreateBlogList(request):
    blog_list = Blog.objects.all()
    context = {
        'object_list': blog_list,

    }

    return render(request, 'blog/createblogs.html', context)

def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse('blog:blog_list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'Catalog/base.html' %}

{% block content %}
<div class="col-12">
  <div class="row">
    <div class="row col-md-12 g-5">
      <div class="card">
        <div class="body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить материал "{{ object.title }}"</p>
            <button type="submit" role="button" tabindex="-1" class="btn btn-danger">
              Удалить
            </button>
            <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">АТМЕНА</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'Catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.title }} ({{ object.slug }})</h1>
    <div class="card" style="width: 18rem;">
        <img src="/media/{{ object.preview }}" class="card-img-top"/>
    </div>
    <p></p>
    <div class="row col">
        <p class="lead">{{ object.body }}</p>
    </div>
    <a href="{% url 'blog:blog_list' %}" type="submit" role="button" class="btn btn-success">К блогам</a>
</div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'Catalog/base.html' %}
{% load my_tags%}
{% block content %}

<div class="col-12">
  <div class="row">
    <div class="row col-md-12 g-3">
      <div class="card">
        <div class="body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" role="button" tabindex="-1" class="btn btn-success">
              {% if object %}
                Сохранить
              <p></p>
              {% else %}
                Создать
              <p></p>
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'Catalog/base.html' %}

{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Всевышний блог</h1>
    <p class="lead"></p>
</div>
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить блог</a>
    {% endif %}
    {% if user.is_superuser %}
    <a class="btn btn-outline-primary" href="{% url 'blog:createblogs' %}">Редактировать список блогов</a>
    {% endif %}
</div>
<div class="container">
    <div class="row  col-8-mb-4">
        {% if user.is_authenticated %}
        {% for object in object_list %}
        {% if object.is_published %}
        <div class="card" style="width: 25rem;">
            <p></p>
            <img src="/media/{{ object.preview}}" width="250" height="300" class="card-img-top"/>
            <div class="card-body">
                <h5 class="card-title">{{ object | title }}</h5>
                <p class="card-text">{{ object.body | truncatewords:10| linebreaks }}</p>

                <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-primary">Почитаем</a>
                <a href="{% url 'blog:edit' object.pk %}" class="btn btn-primary">Редактировать</a>
                <a href="{% url 'blog:delete' object.pk %}" class="btn btn-primary">Удалить</a>

            </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/createblogs.html
{% extends 'Catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% for object in object_list %}
    <div class="card" style="width: 25rem;">
        <p class="lead">{{ object.title }}</p>
        <p></p>
        <div class="card-footer">
            {% if object.is_published %}
            <a class="btn btn-danger" href="{% url 'blog:toggle_activity' object.pk%}">Деактивировать
                блог</a>
            {% else %}
            <a class="btn btn-success" href="{% url 'blog:toggle_activity' object.pk%}">Активировать
                блог</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}