Catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from Catalog.apps import CatalogConfig
from Catalog.views import HomeListView, ContactsView, CatalogListView, ProductDetailView, ProductUpdate, \
    ProductDeleteView, ProductCreateView, toggle_activity_product, ProductSaleView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('catalog', CatalogListView.as_view(), name='catalog'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product/<int:pk>/', cache_page(120)(ProductDetailView.as_view()), name='product'),
    path('update_product/<int:pk>', ProductUpdate.as_view(), name='update_product'),
    path('delete_product/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('create_product/', ProductCreateView.as_view(), name='create'),
    path('create_product_view/', ProductSaleView, name='create_product_view'),
    path('activity_product/<int:pk>/', toggle_activity_product, name='toggle_activity_product'),
    path('category_list/', CategoryListView.as_view(), name='category_list')
]

blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView, CreateBlogList, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list',BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>',BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('createblogs/', CreateBlogList, name='createblogs'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls', namespace='Catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, UserPasswordResetView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm/<str:token>/', email_verification, name='confirm'),
    path("password-reset/", UserPasswordResetView.as_view(), name="password_reset"),
]

Catalog/models.py
from django.db import models



from users.models import NULLABLE, User


class Task(models.Model):
    title = models.CharField("Название", max_length=50)
    task = models.TextField("Описание")

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")
    description = models.CharField(max_length=100, verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")
    description = models.CharField(max_length=200, verbose_name="Описание")
    views_count = models.IntegerField(default=0, verbose_name="просмотры")
    preview = models.ImageField(
        upload_to="products/foto",
        blank=True,
        null=True,
        verbose_name="Изображение(превью)",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
    )
    purchase_price = models.FloatField(
        verbose_name="Цена за покупку",
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания(записи в БД)",
    )
    updated_at = models.DateField(
        auto_now=True,
        verbose_name="Дата последнего изменения(записи в БД)",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Продается'
    )
    owner = models.ForeignKey(User, verbose_name='Создатель', help_text='Укажите создателя продукта',on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "purchase_price", "category", "created_at", "is_active", "owner"]
        permissions = [
            ('can_edit_description', 'Может менять описание Продукта'),
            ('can_edit_category','Может менять категорию любого продукта'),
            ('can_edit_toggle', 'Может отменять публикацию продукта')
        ]

class Version(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_versions"
    )
    version_number = models.IntegerField(default=1, verbose_name="Номер версии")
    name_version = models.CharField(max_length=20, verbose_name="Имя версии")
    current_version = models.BooleanField(
        default=True, verbose_name="Признак текущей версии"
    )
    def __str__(self):
        return f'{self.name_version} {self.version_number}'
    class Meta:
        verbose_name = "Версия продукта"
        verbose_name_plural = "Версии продуктов"
        ordering = ['product', 'version_number', 'name_version', 'current_version']

Catalog/forms.py
from django import forms
from django.forms import BooleanField

from Catalog.models import Product, Version

forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

class StyleFormMixin:
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'is_active', 'purchase_price', 'preview', 'owner' )

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        for word in forbidden_words:
            if  word in cleaned_name:
                raise forms.ValidationError('Содержит запрещенные слова')

        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data['description']
        for word in forbidden_words:
            if word in cleaned_description:
                raise forms.ValidationError('Содержит запрещенные слова')

        return cleaned_description

class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
         model = Version
         fields = '__all__'

class ProductModeratorForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_active')

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        for word in forbidden_words:
            if  word in cleaned_name:
                raise forms.ValidationError('Содержит запрещенные слова')

        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data['description']
        for word in forbidden_words:
            if word in cleaned_description:
                raise forms.ValidationError('Содержит запрещенные слова')

        return cleaned_description

Catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, View, DetailView, UpdateView, DeleteView, CreateView


from Catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from Catalog.models import Product, Version, Category
from Catalog.service import get_category_from_cache


class HomeListView(ListView):
    model = Product
    template_name = 'Catalog/home.html'


class ContactsView(View):
    def get(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f' {name} ({phone}): {message})')

        return render(request, 'Catalog/contacts.html')


class CatalogListView(ListView):
    model = Product
    template_name = 'Catalog/catalog.html'


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ProductUpdate(LoginRequiredMixin,UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('Catalog:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm('Catalog.can_edit_description') and user.has_perm('Catalog.can_edit_category'):
            return ProductModeratorForm
        raise PermissionDenied

class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('Catalog:catalog')

    def test_func(self):
        return self.request.user.is_superuser

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('Catalog:catalog')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()

        return super().form_valid(form)




def ProductSaleView(request):
    product_list = Product.objects.all()
    context = {
        'object_product': product_list,

    }

    return render(request, 'Catalog/create_products_view.html', context)


def toggle_activity_product(request, pk):
    Product_item = get_object_or_404(Product, pk=pk)
    if Product_item.is_active:
        Product_item.is_active = False
    else:
        Product_item.is_active = True

    Product_item.save()

    return redirect(reverse('Catalog:catalog'))


class CategoryListView(ListView):
    model = Category
    template_name = 'Catalog/category_list.html'

    def get_queryset(self):
        return get_category_from_cache()

Catalog/templates/Catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>ИИИИИ так</h4>
                    <p class="text-body-secondary">Не справедливость она такая, не найдешь где угадаешь!</p>
                </div>
                {% include 'Catalog/includes/includes.html' %}
            </div>
        </div>
    </div>
    <div class=" navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a URL="https://sky.pro/" class="navbar-brand d-flex ">
                <svg width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                </svg>
                <strong>Skypro</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="btn-group">
                {% if user.is_authenticated %}
                <li><a class="btn btn-outline-secondary" type="button" href="{% url 'users:profile' %}">Профиль</a></li>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <li><button class="btn btn-outline-secondary" type="submit">Выйти</button></li>
                </form>
                {% else %}
                <li><a class="btn btn-outline-secondary" href="{% url 'users:login' %}">Войти</a></li>
                <li><a class="btn btn-outline-secondary" type="button" href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<body>

<div class="container">
    <div class="row col-12">

        {% block content%}
        {% endblock %}

    </div>
</div>

<footer class="pt-4 my-md-5 pt-md-5 px-4 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

Catalog/templates/Catalog/catalog.html
{% extends 'Catalog/base.html' %}

{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'Catalog:create' %}">Добавить продукт</a>
    {% endif %}
    {% if perms.Catalog.can_edit_toggle or is_superuser %}
    <a class="btn btn-outline-primary" href="{% url 'Catalog:create_product_view' %}">Редактировать список продуктов</a>
    {% endif %}
    <a class="btn btn-outline-primary" href="{% url 'Catalog:category_list' %}">Список категорий</a>
</div>
<div class="container">
    <div class="row col-12 px-3">

        {% for object in object_list %}
        {% if object.is_active %}
        <div class="col-4">
            <div class="card mt-3 py-3 shadow-sm" style="height: 40rem;">
                <p></p>
                <img src="/media/{{ object.preview}}" width="250" height="300" class="card-img-top"/>
                <div class="card-body" style="height: 15rem;">

                    <h3 class="mb-0">{{ object.name }}</h3>

                    <p class="card-text">{{ object.description | truncatewords:10| linebreaks }}</p>
                    <strong class="d-inline-block mb-2 text-primary-emphasis">{{ object.purchase_price }} ₽</strong>
                    <div>
                        <a href="{% url 'Catalog:product' object.pk %}" class="btn btn-primary">Почитаем</a>
                        {% if perms.Catalog.change_product or is_superuser or user == object.owner %}
                        <a href="{% url 'Catalog:update_product' object.pk %}" class="btn btn-primary">Редактировать</a>
                        {% endif %}
                        {% if perms.Catalog.delete_student %}
                        <a href="{% url 'Catalog:delete' object.pk %}" class="btn btn-primary">Удалить</a>
                        {% endif %}
                    </div>
                    <div class="card-footer mt-1 ">
                        <li>Просмотры: {{ object.views_count }} </li>
                        {% for version in object.product_versions.all %}
                        {% if version.current_version %}
                        <li>Версия: {{ version }} </li>
                        {% endif %}
                        {% endfor %}
                        <li>Создатель: {{ object.owner }}</li>
                    </div>
                </div>

            </div>
        </div>
        {% endif %}
        {% endfor %}

    </div>
</div>
{% endblock %}

Catalog/templates/Catalog/category_list.html
{% extends 'Catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% for object in object_list %}
    <div class="card" style="width: 25rem;">
        <p class="lead">{{ object.name }}</p>
        <p></p>
        <div class="card-footer">
            <a class="btn btn-success-muted" href="">К списку</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Catalog/templates/Catalog/contacts.html
{% extends 'Catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Catalog/templates/Catalog/create_products_view.html
{% extends 'Catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% for object in object_product %}
    <div class="card" style="width: 25rem;">
        <p class="lead">{{ object.name }}</p>
        <p></p>
        <div class="card-footer">
                {% if object.is_active %}
                <a class="btn btn-danger" href="{% url 'Catalog:toggle_activity_product' object.pk%}">Деактивировать продукт</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'Catalog:toggle_activity_product' object.pk%}">Активировать
                    продукт</a>
                {% endif %}
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

Catalog/templates/Catalog/home.html
{% extends 'Catalog/base.html' %}

{% block content %}

<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="col-lg-6 px-0">
            <h2 class="display-4 fst-italic">Сегодня у вас есть уникальная возможность приобрести незабываемые вещи</h2>
            <p class="lead my-3">Только у нас есть такое невозможное разнообразие </p>
            <p class="lead mb-1"><a href="{% url 'Catalog:catalog' %}" class="text-body-emphasis fw-bold">Посмотреть товары</a></p>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis">Рекламка</strong>
                    <h3 class="mb-0">Рекламочка</h3>
                    <p class="card-text mb-auto">Здесь бы могла быть именно ваша рекламка!!!</p>

                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg"
                         role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                         focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                    </svg>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success-emphasis">Вы не поверите!</strong>
                    <h3 class="mb-0">Рекламы</h3>
                    <p class="mb-auto">Много не бывает!!!))) </p>

                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg"
                         role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                         focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                    </svg>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

Catalog/templates/Catalog/product_confirm_delete.html
{% extends 'Catalog/base.html' %}

{% block content %}
<div class="col-12">
  <div class="row">
    <div class="row col-md-12 g-5">
      <div class="card">
        <div class="body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить материал "{{ object.title }}"</p>
            <button type="submit" role="button" tabindex="-1" class="btn btn-danger">
              Удалить
            </button>
            <a href="{% url 'Catalog:catalog' %}" class="btn btn-warning">АТМЕНА</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Catalog/templates/Catalog/product_detail.html
{% extends 'Catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row mb-2 mt-4">
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary-emphasis">{{ object.purchase_price }} ₽</strong>
                <h3 class="mb-0">{{ object.name }}</h3>
                <p class="card-text mb-auto">{{ object.description }}</p>
                <a href="#" class="btn btn-secondary disabled" tabindex="-1" role="button" aria-disabled="true">Купить</a>
            </div>
            <div class="col-auto d-none d-lg-block">
                <img class='card-img-top' src="{{ object.preview | media_filter }}" width="200" height="250">
            </div>
        </div>
        <div class="card-footer">
            Просмотры: {{ object.views_count }}
            Создатель: {{ object.owner }}
        </div>
    </div>
</div>


{% endblock %}

Catalog/templates/Catalog/product_form.html
{% extends 'Catalog/base.html' %}
{% load my_tags%}
{% block content %}


<div class="row-cols-12 mt-4">
    <form class="row" method="post">
        <div class=" col-6">
            <div class="card">
                <div class="body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" role="button" tabindex="-1" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        <p></p>
                        {% else %}
                        Создать
                        <p></p>
                        {% endif %}
                    </button>

                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">
                        Редактирование версии продукта
                    </h2>
                    <div class="body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                        <hr>
                        {% endif%}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}